### ISSUE TITLE
CCX student can't find their CCX

### ISSUE THREAD

**Issue by pwilkins** [jazkarta/edx-platform#66]
When a student is enrolled but not registered in a CCX, the CCX should be discoverable in the course list or the dashboard, even if the CCX is the only course they are enrolled for. That isn't the case.  When a student activates their edX (not course) registration, they are provided a link to their dashboard, but the dashboard doesn't contain the CCX in which the student is enrolled.  

The student can navigate to the course if they open the course that the CCX is based on, assuming that it is visible in their "find courses" list.

**Comment by cewing** [comment]
This should be fixed now.  @pwilkins can you please reverify this issue and close the ticket if it is no longer valid?

**Comment by pwilkins** [comment]
I tested this today on our sandbox and still have problems.  I enrolled a registered student in a CCX, logged in as the student, and couldn't find the CCX in the student's dashboard.

**Comment by cewing** [comment]
Is the student you enrolled in the CCX also enrolled in the course from which the CCX was created?  That is a requirement of the system at this time.

**Comment by jetej** [comment]
I think this may be fixed by https://github.com/jazkarta/edx-platform/issues/78. Now, only the CCX appears on the student's "Dashboard".

**Comment by jetej** [comment]
This seems to work fine on https://edge.edx.org.  @pdpinch, I believe this ticket can be closed.
